name: Moon Web Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install and Start Moon Binary
        run: |
          # 1. Скачиваем сам бинарник Moon (он маленький и быстрый)
          curl -L -o moon https://github.com
          chmod +x moon
          
          # 2. Запускаем его в фоне в локальном режиме
          # Он сам найдет Docker на раннере и будет штамповать браузеры
          ./moon --local & 
          
          # 3. Ждем пару секунд
          sleep 5
          curl -I http://localhost:4444/status

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
