name: Moon Web Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Moon
        run: |
          docker run -d --name moon \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aerokube/moon:latest --local
          
          sleep 15
          echo "--- MOON LOGS ---"
          docker logs moon
          
          echo "--- CHECKING CONNECTION ---"
          curl -I http://localhost:4444/status

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
