name: Moon Web Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Moon
        run: |
          # Запускаем через переменные среды, но без лишних флагов
          docker run -d --name moon \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e MOON_LOCAL=true \
            -e MOON_FORCE_ID=1 \
            aerokube/moon:latest
          
          sleep 20
          docker logs moon
          curl -I http://localhost:4444/status

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
